name: 'selenium-bots'
services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    ports:
      - ${HUB_PORT}:4444
    environment:
      - SE_VNC_PASSWORD=${VNC_PASSWORD}

  chrome:
    image: selenium/node-chrome:latest
    shm_size: '2gb'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--enable-managed-downloads true

  firefox:
    image: selenium/node-firefox:latest
    shm_size: '2gb'
    volumes:
      - /dev/shm:/dev/shm
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_OPTS=--enable-managed-downloads true

  runner:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: runner
    volumes:
      - .:/usr/src/selenium-bots
    environment:
      - PYTHONPATH=/usr/src/selenium-bots
    working_dir: /usr/src/selenium-bots
    depends_on:
      - selenium-hub
      - chrome
      - firefox
    command: sh -c "while true; do sleep 1000; done"
